name: roadaid_payment_app
description: RoadAid Payment Application
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.2.0

flutter:
  uses-material-design: true
